spring:
  cloud:
    function:
      definition: generateOnKafkaTopicIndividual;generateOnKafkaTopicBusiness
    stream:
      kafka:
        binder:
          brokers: 13.235.73.172:9092
      bindings:
        producer-out-0:
          destination: individual
        producer-out-1:
          destination: business
        generateOnKafkaTopicBusiness-out-0:
          destination: business
        generateOnKafkaTopicIndividual-out-0:
          destination: individual

kafka-constants:
  topics:
    individual: producer-out-0
    business: producer-out-1

server:
  port: 8083